### ISSUE TITLE
Changer "Indice de qualité de l'air"

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante#104]
Mettre "Indice ATMO de la qualité de l’air" pour que ce soit plus clair pour l'utilisateur.

Peut être mettre ATMO en gras et en couleur ?

Le faire clignoter ?

**Comment by MarinePurson** [comment]
Quel intérêt tu vois derrière ça ? (vraie question)

**Comment by florianpanchout** [comment]
Aucun, c'est une demande Atmo que m'a transmise Marie

Je trouve personnellement ça inutile, idiot et n'allant pas dans le sens de la compréhension utilisateur.
