### ISSUE TITLE
[landing médecins] Dans "Pour qui est Recosanté" remplacer "Mais surtout" par "Mais aussi"

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#11]

**Comment by florianpanchout** [comment]
Fait mais ça n'a pas trop de sens : "Pour tous les citoyens" => "Mais aussi"

**Comment by annepoirot** [comment]
Oui effectivement je vois ce que tu veux dire. Dans ce cas on peut commencer directement par "Pour les personnes ayant une pathologie...."

**Comment by florianpanchout** [comment]
C'était le texte de départ. Retour de Livio : 

> imho : on se ferme inutilement des portes en disant que c'est d'abord un truc de spécialistes.

> je dirais plutôt :
> 1. c'est pour tout le monde
> 2. et en particulier pour les personnes qui ont une pathologie parce qu'on va pouvoir personnaliser les recos

**Comment by annepoirot** [comment]
Oui pardon je voulais dire qu'on met les deux : 
- Pour tous les citoyen·ne·s qui souhaitent se protéger des impacts de la qualité de l’air sur leur santé et contribuer à réduire la pollution de l’air.

- Pour les personnes ayant une pathologie respiratoire et/ou des allergies, car ils sont ceux pour qui la qualité de l’air a un impact direct sur la santé.

=> Sinon on garde "Mais surtout" avant, ce n'est pas dramatique

**Comment by florianpanchout** [comment]
Fait
