### ISSUE TITLE
Décision hébergement front

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante#111]
Actuellement le front est hébergé sur Gatsby Cloud. 

- Est ce que c'est la solution que l'on souhaite utiliser long terme ?
- Si oui, il faut un compte payant ($20 / mois) pour avoir deux utilisateurs dessus
- Si oui, il faut réfléchir à une solution pour le certificat SSL (installé manuellement mais valide que 90 jours)

**Comment by l-vincent-l** [comment]
On doit renouveler le certificat manuellement parce qu’il ne trouve pas l’entrée DNS qu’il veut ou bien il y a une autre raison ?

**Comment by florianpanchout** [comment]
Compte Gatsby Cloud passé en payant ($20 / mois, paiement au mois). 

Je t'ai ajouté en admin @l-vincent-l.

**Comment by florianpanchout** [comment]
@annepoirot Pourquoi avoir fermé cette issue ? Vous avez pris une décision ?

**Comment by florianpanchout** [comment]
@l-vincent-l Le plan Gatsby Cloud actuel ne permet d'avoir que deux comptes. Je t'ai passé owner il y a quelques jours. Tu pourras me supprimer à ton retour et ajouter @fcoufour à ma place

**Comment by fcoufour** [comment]
C'est noté, Florian. S'il y a des choses à savoir dans la gestion des certificats, n'hésitez pas. 2 certificats émis par 2 autorités différentes pour app et api à ce que je vois. Vous avez un compte chez Zero SSL pour le frontend ?
Quel est le statut pour le choix de l'hébergement frontend ?

**Comment by florianpanchout** [comment]
Pas grand chose à savoir de plus que cette conversation. 

Pour le front-end, Gatsby Cloud refuse de générer un certificat SSL automatiquement (car il attend un CNAME alors que les beta.gouv.fr utilisent un ALIAS). On a donc utilisé zerossl pour en générer un. Il expire le 12 janvier.

Il n'y a pas eu de décision de prise pour le front-end. Je vous laisse gérer ça @l-vincent-l et toi, vu que vous serez les deux impactés par cette décision

**Comment by fcoufour** [comment]
Qui a accès au compte Zero SSL ? car ça va venir vite 😄
Il y a une raison particulière pour laquelle vous n'avez pas utilisé le certificat Let's Encrypt de l'API ?

**Comment by florianpanchout** [comment]
Celui de l'api n'est pas wildcard je crois ?

**Comment by fcoufour** [comment]
Aucun des 2 n'est wildcard visiblement mais ça simplifierait peut-être la gestion d'avoir une seul certificat Zero SSL ou Let's Encrypt en mode wildcard ou avec le domaine principal et son sous-domaine pour plus de restriction. On en reparle tous les 4 de vive voix si vous le voulez bien.

**Comment by florianpanchout** [comment]
Il s'avère que 90 jours !== 3 mois : le certificat expirait lundi...

J'en ai généré et installé un nouveau (qui expire le 8 avril). Toujours via l'offre gratuite zeroSSL
