### ISSUE TITLE
Prévenir l'utilisateur que l'infolettre hebdomadaire n'est pas encore active

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante#130]
Proposition : ajouter un texte à ce niveau : 

![Screenshot 2021-10-20 at 10 44 15](https://user-images.githubusercontent.com/8115933/138059825-7e2c80fc-97a0-48fc-8845-5c7a12695a0c.png)

Aucune idée d'un wording compréhensible pour l'usager par contre

**Comment by mariegasnier1** [comment]
Concernant le message, je mettrais "à venir" sur la vignette bleue puis je remplacerais "Vous recevrez un email par semaine" par "Abonnez-vous aujourd'hui pour recevoir un email par semaine une fois les évolutions prêtes" (dans l'idée)

**Comment by MarinePurson** [comment]
Je suis d'accord avec @mariegasnier1 Marie sur le terme "recommandations" qui n'est pas forcément le plus parlant. Mais j'ai aussi en tête un enjeu de cohérence avec le nom du produit qui fait qu'on ne peut pas disparaître ce terme...

Le terme de "message de prévention" est un terme de travail, pas un terme grand public de communication.
Je resterais dans ce cas sur quelque chose de générique, type "M'abonner à la lettre d'information hebdomadaire".

**Comment by mariegasnier1** [comment]
Oui très bien pour la lettre d'info. Je préciserais toutefois qu'il s'agit d'un contenu personnalisé sur cette page, d'où les questions suivantes

**Comment by MarinePurson** [comment]
On peut préciser "des conseils adaptés à vos habitudes", mais on ne peut pas parler de personnalisation tant qu'on est pas en données de santé

**Comment by mariegasnier1** [comment]
Oui je trouve aussi
