### ISSUE TITLE
Prévenir les utilisateurs que les notifications web ne fonctionne pas sur iOS

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante#137]
iOS ne supporte pas l'api push (https://caniuse.com/push-api)

**Comment by annepoirot** [comment]
Sur le nombre d'abonnés, la semaine dernière 178 personnes étaient abonnés aux notifications, mais seulement 96 les ont acceptées.

**Comment by MarinePurson** [comment]
Est-ce que @annepoirot ou @florianpanchout vous pouvez ajouter les infos qu'il faut faire passer à l'utilisateur/notification ici : https://app.sendinblue.com/editor/newsletters/1537

Je fais une repasse ensuite.

**Comment by MarinePurson** [comment]
J'ai ajouter une mention pour indiquer aux utilisateurs qu'ils sont sous iOS et inscrits aux notifs, il faut qu'ils modifient leur profil. Est-ce que tu peux ajouter le bouton qui va bien pour les renvoyer vers la modif de profil ?

**Comment by florianpanchout** [comment]
C'est fait. On attend plus que la résolution de https://github.com/betagouv/recosante/issues/136 avant de pouvoir l'envoyer non ?

**Comment by florianpanchout** [comment]
(d'ailleurs l'envoi est géré ici : https://github.com/betagouv/recosante/issues/123, je ferme cette issue
