### ISSUE TITLE
Automatiser le déploiement du site

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#138]
Je ne sais pas si je fais quelque chose de mal, mais lorsque j'ajoute un logo maintenant sur la page partenaire, ça ne fonctionne pas.
Exemple de comit : https://github.com/betagouv/recosante/commit/3e5f2965469b0328af59460e5f6593338ce0e760

**Comment by florianpanchout** [comment]
C'est bon, le déploiement est maintenant automatique lorsque l'on push sur ce repo
