### ISSUE TITLE
Pas de recommandations pollen affichée sur le dashboard

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#140]
<img width="1020" alt="Capture d’écran 2021-11-02 à 15 40 47" src="https://user-images.githubusercontent.com/63290799/139869147-3c8046d8-7e53-4e5a-84c0-c49174b622ee.png">

**Comment by l-vincent-l** [comment]
C’est bon, le problème est résolu
![image](https://user-images.githubusercontent.com/2757318/140096289-b91afeec-2e09-4adb-92ff-c1a5210c7cdb.png)

**Comment by mariegasnier1** [comment]
Il y a un autre souci pour la catégorie "moyen" 

![image](https://user-images.githubusercontent.com/89836591/140533118-8a555f94-7d8f-485e-9d56-d12acf37e765.png)

**Comment by mariegasnier1** [comment]
Un autre souci pour le niveau moyen 

![Uploading image.png…]()

**Comment by mariegasnier1** [comment]
![image](https://user-images.githubusercontent.com/89836591/140533318-345336dd-34e2-4926-86f5-0d50799f346c.png)

**Comment by mariegasnier1** [comment]
Un autre souci pour le risque moyen

**Comment by annepoirot** [comment]
C'était l'affichage dans l'admin qui posait problème. 
Vincent a modifié, maintenant les recommandations pollens sont montrées soit pour 0, soit pour 1 à 3, soit pour 4 à 6. 
Donc ça devrait régler le problème.
