### ISSUE TITLE
Faire un visuel pour l'invitation de l'open lab

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#141]
On écrit le contenu puis on aura besoin de @florianpanchout pour le visuel :D

**Comment by MarinePurson** [comment]
Le contenu de l'invitation est disponible ici : https://pad.incubateur.net/a6Pb3AGkQWGEMweWDgPbhg?both

Si tu as l'impression qu'il faut plus de niveaux de titres, etc. n'hésite pas à nous dire @florianpanchout.
Possible d'avoir quelques chose d'ici mercredi pour envoyer avant le grand week-end ?

**Comment by florianpanchout** [comment]
C'est possible mais il va me falloir plus de contexte aha. C'est pour imprimer ? Pour envoyer par mail ? Vous voulez des images du produit dedans ?

**Comment by MarinePurson** [comment]
Il s'agit d'invitations qu'on va envoyer à une vingtaine de prescripteurs du service + prospects pour l'openlab qu'on organise le 7 décembre.

Ces invitations seront envoyées par email. On voudrait les envoyer depuis nos adresses et pas depuis Sendinblue. Du coup je me demande si c'est plus pertinent d'avoir un PDF ou un visuel .jpg ?

D'un point de vue graphique, pas forcément besoin d'avoir un visuel du produit pour moi... J'ai l'impression qu'on peut simplement faire une invitation simple qui reprend les codes de l'identité (logo, typo, couleurs).

**Comment by florianpanchout** [comment]
Si elles n'ont pas pour but d'être imprimées, est ce que ça ne serait pas mieux de mettre les infos directement dans le mail ? Je ne suis pas sur de la pertinence de faire un pdf ici

**Comment by MarinePurson** [comment]
En fait on trouvait collectivement (Anne, Pierre, Emilien et moi) que c'est pas mal d'avoir un effet "invitation" qui formalise les choses et a une dimension plus valorisante pour nos interlocuteurs.

@annepoirot tu en penses quoi ?

**Comment by florianpanchout** [comment]
Une proposition de pdf :
[Invitation.pdf](https://github.com/betagouv/recosante/files/7504879/Invitation.pdf)

Je suis toujours très peu convaincu par la valeur ajoutée d'une pièce jointe ici, comparé aux problèmes que cela apporte (responsive, complexification de l'accès à l'information, etc...)
