### ISSUE TITLE
Bug interface pour Basse-Terre

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante#143]
Lorsque l’on recherche Basse-Terre dans la barre de recherche on est renvoyé vers une page avec une erreur 500

https://recosante.beta.gouv.fr/place/97105/basse-terre/

**Comment by florianpanchout** [comment]
Toutes les url avec des tirets étaient affectées. Visiblement depuis que j'ai traité https://github.com/betagouv/recosante/issues/138.

J'ai relancé un build et ça a corrigé le problème.
