### ISSUE TITLE
Intégration du potentiel radon 

### ISSUE THREAD

**Issue by mariegasnier1** [betagouv/recosante#146]
- [x] Designer le picto
- [x] Intégrer dans le dashboard 

L'encadré précisera la valeur du potentiel radon (Catégorie 1, 2 ou 3), et une recommandation différente selon la zone (les catégories 1 et 2 auront la même recommandation)  : 
- Catégorie 1 et 2 : Pour améliorer la qualité de l’air dans votre logement, aérer 10 minutes matin et soir. 
- Catégorie 3 : Pour réduire les niveaux de radon et garantir une bonne qualité de l’air dans votre logement, aérer régulièrement les pièces et s’assurer du bon fonctionnement du système de ventilation.

![image](https://user-images.githubusercontent.com/89836591/142634104-5ee76fb7-2299-499a-ab44-c507d8bee549.png)

**Comment by mariegasnier1** [comment]
Pour le picto, le plus intuitif est de mettre une maison en indiquant quel niveau de catégorie (1 2 ou 3). Une petite loupe précisera le radon (pas Rn) 

![image](https://user-images.githubusercontent.com/89836591/142634359-61eddcbc-30ce-42f7-90d1-16ffe38e7d9c.png)

**Comment by mariegasnier1** [comment]
**Enfin, pour préciser ce qu'est le potentiel radon :** 
Le radon est un gaz radioactif naturel présent dans le sol et les roches. Il est produit par la désintégration du radium issu de la famille de l’uranium, présent partout dans les sols et plus fortement dans les sous-sols granitiques et volcaniques. Le radon est classé cancérigène certain pour le poumon par le Centre international de recherche sur le cancer depuis 1987. Le potentiel radon fournit un niveau de risque relatif à l'échelle d'une commune. Toutefois, il ne présage en rien des concentrations en radon présentes dans votre habitation : celles-ci dépendent de multiples autres facteurs (étanchéité de l'interface entre le bâtiment et le sol, taux de renouvellement de l'air intérieur, etc.).
La cartographie du potentiel du radon à partir des formations géologiques est établie par l’Institut de radioprotection et de sûreté nucléaire (IRSN). Elle conduit à classer les communes en 3 catégories :
Catégorie 1
Ces communes sont localisées sur les formations géologiques présentant les teneurs en uranium les plus faibles. Sur ces formations, une grande majorité de bâtiments présente des concentrations en radon faibles.
Catégorie 2
Ces communes sont localisées sur des formations géologiques présentant des teneurs en uranium faibles mais sur lesquelles des facteurs géologiques particuliers peuvent faciliter le transfert du radon vers les bâtiments.
Catégorie 3
Ces communes sont celles qui, sur au moins une partie de leur superficie, présentent des formations géologiques dont les teneurs en uranium sont estimées plus élevées comparativement aux autres formations. La probabilité de présence de radon dans les bâtiments de ces communes est plus importante. 
En savoir plus (renvoie vers la page de l'IRSN sur le radon : https://www.irsn.fr/FR/connaissances/Environnement/expertises-radioactivite-naturelle/radon/Pages/5-cartographie-potentiel-radon-commune.aspx#.YZet_vnMK70

**Abonnement non disponible :** 
Donnée statique 
Le potentiel radon ne fluctue pas dans le temps. Le potentiel radon a été cartographié en 2010 par l'Institut de Radioprotection et de Sûreté Nucléaire. 
En savoir plus (https://solidarites-sante.gouv.fr/sante-et-environnement/batiments/article/radon)

**Comment by florianpanchout** [comment]
Première proposition pour le picto : 

![Screenshot 2021-11-23 at 11 39 01](https://user-images.githubusercontent.com/8115933/143009935-af449819-700a-4d6d-9154-0d2dd607de86.png)

J'ai enlevé les chiffres et le mot Radon pour rester cohérents avec les autres pictos ("Radon" ne serait de toute façon pas très lisible à cette taille)

**Comment by mariegasnier1** [comment]
Merci Florian 
Je comprends. Très bien dans ce cas ! 
Juste, à la place de "données statiques", je mettrais "Abonnement non disponible" en précisant ensuite pourquoi l'utilisateur ne peut pas s'abonner

**Comment by florianpanchout** [comment]
To-do pour la mise en ligne du radon : 

Front : 
- [ ] Design du picto
- [ ] Intégration du picto
- [ ] Modification des textes "Abonnement non disponible" et "Potentiel Radon"

Back : 
- [ ] Modification des labels ("Faible" => "Catégorie 1", etc)
- [ ] Modification des recommandations (voir https://github.com/betagouv/recosante/issues/146#issue-1058556221)

**Comment by florianpanchout** [comment]
@l-vincent-l @annepoirot Finalement j'ai eu le temps de m'en occuper. C'est visible sur le staging : https://recosantestaging.gatsbyjs.io/place/75056/paris/

Il suffira d'accepter cette PR (https://github.com/betagouv/recosante/pull/147) pour mettre le front en prod.

**Comment by mariegasnier1** [comment]
Je viens de voir les couleurs. On s'était dit un dégradé de orange, possible pour toi de modifier ça ?

**Comment by florianpanchout** [comment]
Possible, mais est ce que l'on veut vraiment ajouter une palette de couleurs en plus sur cette page ?

**Comment by mariegasnier1** [comment]
Non pas utile. Une seule couleur de orange me convient.

**Comment by mariegasnier1** [comment]
![image](https://user-images.githubusercontent.com/89836591/143060176-c4322862-e9b3-49e7-b562-083522f9acad.png)

Certaines communes affichent une recommandation autre que celle définie. Pour rappel : 

- Catégorie 1 et 2 : Pour améliorer la qualité de l’air dans votre logement, aérer 10 minutes matin et soir.
- Catégorie 3 : Pour réduire les niveaux de radon et garantir une bonne qualité de l’air dans votre logement, aérer régulièrement les pièces et s’assurer du bon fonctionnement du système de ventilation.

Merci Florian !

**Comment by annepoirot** [comment]
Yes, c'est parce que dans l'admin on a encore les anciennes recommandations. Donc tu me confirmes @mariegasnier1 qu'on a que deux recommandations en tout, celles qui sont dans ton message précédent ?

**Comment by mariegasnier1** [comment]
D'accord, merci ! Oui c'est ça, que deux recommandations.

**Comment by annepoirot** [comment]
C'est fait !

**Comment by annepoirot** [comment]
Il ne reste que la modification de termes (faible qui deviens catégorie 1, moyen devient catégorie 3 et élevé catégorie 3), c'est du côté back du coup @l-vincent-l ?

**Comment by florianpanchout** [comment]
J'ai modifié les couleurs pour utiliser du orange pour les 3 catégories

**Comment by annepoirot** [comment]
A faire @l-vincent-l : 
- modifier les termes faible/moyen/élevé
- accepter cette PR (#149) pour mettre le front en prod
