### ISSUE TITLE
Clarifier la fréquence dans le processus d'inscription

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#157]
Parler de vigilance + expliciter en dessous 
voir issue #131

**Comment by annepoirot** [comment]
Je passe cette issue car c'était un objectif du mois de décembre, si tu as le temps @florianpanchout :)

**Comment by florianpanchout** [comment]
Done. J'ai modifié les textes pour qu'ils rentrent dans l'interface (supprimé le début : "Vous recevrez les indicateurs"). 

J'ai aussi modifié le texte à propos des indicateurs sur la home en conséquence (et les textes de partage RS)
