### ISSUE TITLE
Ajouter une phrase dans "Qui sommes nous"

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#16]
à ajouter sur la home Recosanté, dans "Qui sommes-nous ?", à la suite de la première phrase :

Le service est en phase de construction, il évolue de façon continue selon les retours des utilisateurs.

**Comment by florianpanchout** [comment]
Fait

(Pour info la plupart des contenus se trouvent ici : https://github.com/betagouv/recosante/tree/master/content/texts)

**Comment by annepoirot** [comment]
Ok parfait merci je pourrai modifier moi même à l'avenir comme ça :)
