### ISSUE TITLE
Modifier l'écriture des polluants dans le dashboard

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#161]
Dans les descriptions des polluants, pour l'ensemble des polluants :

<img width="707" alt="Capture d’écran 2021-12-20 à 10 17 19" src="https://user-images.githubusercontent.com/63290799/146743320-b597cbb4-5e05-48a1-9158-cebcf019049e.png">

Il faut que le 2 soit en indice et non en exposant (retour d'ATMO).

**Comment by florianpanchout** [comment]
Visible sur le staging (ce sera en prod en même temps que la vigilance météo)
