### ISSUE TITLE
Texte modal Vigilance Météo

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante#162]
Quel est le texte qui doit s'afficher dans la modal Vigilance Météo ? (au clic sur `(?)` )

**Comment by MarinePurson** [comment]
On pourrait rédiger quelque chose sur la base de cette page : https://vigilance.meteofrance.fr/fr/guide-vigilance-meteo
@annepoirot d'après vos échanges avec Météo France, tu penses qu'on peut réécrire et réduire sans faire valider ?

**Comment by MarinePurson** [comment]
Et voilà : https://pad.incubateur.net/XblZ8il0QVSWM-4jRh7ZQQ

**Comment by florianpanchout** [comment]
C'est intégré !
