### ISSUE TITLE
Modifier les visuels Recosanté avec la vigilance météo

### ISSUE THREAD

**Issue by MarinePurson** [betagouv/recosante#165]
- [x] Visuel meta du site
- [ ] Kit de com

**Comment by florianpanchout** [comment]
Meta modifiée. Je ne crois pas avoir à changer le kit de com ?

**Comment by MarinePurson** [comment]
Je viens de checker et c'est bon en effet, je pensais qu'on avait encore des visuels avec des pictos grisés ;) ! Merci !
