### ISSUE TITLE
Icône Avalanches absente

### ISSUE THREAD

**Issue by fcoufour** [betagouv/recosante#166]
Absence d'icône dans le cas d'Avalanches quelque soit la couleur de la vigilance, remplacée par le texte alt.

<img width="614" alt="vigilance-orange-chambery" src="https://user-images.githubusercontent.com/23194091/147640060-5e86cdab-deb3-4a26-a09a-d13cb4600464.png">

Visible ici aujourd'hui le 29/12/2021 :
https://recosante.beta.gouv.fr/place/73065/chambery/
https://recosante.beta.gouv.fr/place/38185/grenoble/
https://recosante.beta.gouv.fr/place/74010/annecy/

Hypothèse : erreur de singulier / pluriel sur le nom du phénomène.

Tout schuss !

**Comment by florianpanchout** [comment]
C'est corrigé (effectivement avalanche => avalancheS)

**Comment by fcoufour** [comment]
LGTM :+1:
