### ISSUE TITLE
Affichage de plusieurs vigilances pour le même phénomène 

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante#169]
Est ce que c'est utile d'afficher comme ici Avalanches en jaune et en orange ? C'est logique si l'on avait des horaires pour l'un ou l'autre mais ici vu que l'on a décidé d'afficher le plus haut niveau de la journée, est il vraiment pertinent d'afficher le niveau jaune ? 

![Screenshot 2021-12-29 at 15 32 50](https://user-images.githubusercontent.com/8115933/147672877-95291ea8-284f-4355-bb0c-1f03b9b325ff.png)

**Comment by fcoufour** [comment]
Je partage l'avis que suggère la question 😄. Peut-être faudrait-il aussi revoir l'ordre par couleur (rouge en premier puis orange puis jaune) puis éventuellement par type de phénomène.

**Comment by florianpanchout** [comment]
J'ai à minima changé l'ordre (rouge => orange => jaune)

**Comment by florianpanchout** [comment]
J'ai fait en sorte de n'afficher en front que la vigilance la plus importante pour un même phénomène. Par contre je ne retrouve plus de date/commune ou le cas se produisait...

**Comment by fcoufour** [comment]
J'avais eu le temps de tester le changement d'ordre en prod pour Chambéry, Annecy, Grenoble mais pas le filtrage.
C'était en milieu de journée le 29/12. J'ai vu que l'API pouvait prendre une date en paramètre, c'est avec cela que tu ne reproduis pas ? On peut en parler tout à l'heure.

**Comment by annepoirot** [comment]
<img width="546" alt="Capture d’écran 2022-01-10 à 16 03 38" src="https://user-images.githubusercontent.com/63290799/148788049-b5d6a30c-63eb-4f2c-9442-211535061bcf.png">
Ca bug à nouveau il me semble @florianpanchout ?

**Comment by florianpanchout** [comment]
Yep, vu que le paramètre date ne fonctionnait (ne fonctionne ?) pas, je n'ai pas pu tester. Ça devrait être bon maintenant

**Comment by fcoufour** [comment]
C'est développé mais pas encore publié. Après la prochaine mise en prod back-end, il sera possible de reproduire une visite à une date passée. Il faudra ajouter un paramètre de temps pour sélectionner un horaire spécifique, sinon ce sera la dernière publication Météo France de la journée qui sera utilisée.
