### ISSUE TITLE
[landing médecins] changer le visuel de la NL pour mettre le RAEP en fonction du département 

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#17]
Actuellement le visuel montre que le RAEP est donné en IDF ce qui est incorrect. 

Le mieux serait de changer la ville et le département car si on met Paris on aura deux fois à Paris ce qui ne montre pas que la qualité de l'air est sur la ville et le risque allergique sur le département. 

On peut mettre ce que tu veux, ex: Toulouse et en Haute-Garonne ?

**Comment by florianpanchout** [comment]
J'ai changé le visuel (landing et landing médecin)
