### ISSUE TITLE
Ajout de recommandations en cas de vigilance verte et jaune

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#171]
J'ai ajouté deux recommandations en cas de vigilance verte et jaune pour apporter plus de contenu. 

Vigilance verte : Pas de vigilance particulière aujourd'hui.
Vigilance jaune : Des phénomènes habituels dans la région mais occasionnellement et localement dangereux sont prévus aujourd'hui. Soyez attentifs si vous pratiquez des activités sensibles au risque météorologique ou exposées aux crues.

=> Est-ce qu'il y a quelque chose d'autre à rajouter pour qu'elles s'affichent ?

**Comment by fcoufour** [comment]
J'en ai discuté avec @l-vincent-l. A date, il n'y a que les recommandations spécifiques à un phénomène qui sont envoyées via l'API, pas les recommandations générales donc il y un petit morceau de code à écrire pour que ce soit le cas de la même manière que pour les autres cartes. Ca donnerait visuellement :

- en cas de vigilance verte
<img width="606" alt="vigilance-verte-reco" src="https://user-images.githubusercontent.com/23194091/148078755-2c1e679b-a357-47c5-9396-a80b9b5b7bfd.png">

- en cas de vigilance jaune
<img width="616" alt="vigilance-jaune-reco" src="https://user-images.githubusercontent.com/23194091/148076890-21acb412-1268-41df-8df2-1fc712fdc5e3.png">

T'en penses quoi @florianpanchout ?

A voir si on ne fait pas qqch du même genre pour vigilance orange et rouge.

**Comment by florianpanchout** [comment]
Yep, c'est déjà ce qui est prévu en front. Si je reçois une recommandation de l'api au niveau global je l'affiche.

Je ne pense pas que ça soit pertinent de mettre une recommandation globale pour les niveaux orange et rouge.

(À noter que l'on affiche "Pas de vigilance" et non pas "Vigilance verte)

**Comment by fcoufour** [comment]
Je pensais à qqch du genre pour orange par exemple avec 2 états :

![vigilance-orange-reco-1](https://user-images.githubusercontent.com/23194091/148090758-2f37fa86-1044-4680-b76c-cd1f1a653ae2.png)

![vigilance-orange-reco-2](https://user-images.githubusercontent.com/23194091/148090775-a1625269-e626-47ae-bf7d-36d6cf869892.png)

**Comment by annepoirot** [comment]
Justement je me demandais pour la vigilance verte, est-ce qu'on ne mettrais pas "Vigilance verte" au lieu de "Pas de vigilance" si en dessous s'affiche la recommandation ?

> Yep, c'est déjà ce qui est prévu en front. Si je reçois une recommandation de l'api au niveau global je l'affiche.
> 
> Je ne pense pas que ça soit pertinent de mettre une recommandation globale pour les niveaux orange et rouge.
> 
> (À noter que l'on affiche "Pas de vigilance" et non pas "Vigilance verte)

**Comment by fcoufour** [comment]
2 options à mon sens :
- Pas de vigilance particulière, Soyez attentif, Soyez très vigilant, Vigilance absolue
- Vigilance verte, Vigilance jaune, Vigilance orange, Vigilance rouge
mais pas un mélange des 2

**Comment by annepoirot** [comment]
Du coup dans ta proposition de visuels @fcoufour, c'est quand on clique sur "pluie-innondation" que s'affiches les recommandations spécifiques à ce phénomène ?

**Comment by fcoufour** [comment]
En effet, c'était l'idée. J'ai repris le design existant. On pourrait mettre plus d'affordance (comme disent les jeunes branchés) sur "Pluie-Inondation" et atténuer un peu les recommandations particulières. Y'a qqch qui te déplait @florianpanchout ?

**Comment by florianpanchout** [comment]
Nope, je préfère (largement) cette version si elle passe auprès de Météo France. J’afficherais la recommandation phénomène dans une modal (au clic sur le phénomène). Ça simplifierais la hiérarchie d'information et permettrais aussi d’afficher les détails horaires.

C’était d’afficher concurremment une recommandation globale et par phénomène qui me posait problème.

**Comment by MarinePurson** [comment]
Je suis d'accord avec la proposition de Florian sur le modal pour la recommandation phénomène car il est impératif de les conserver.

Et ok pour vos propositions sur l'affichage des vigilances verte et orange.

**Comment by fcoufour** [comment]
En conclusion, j'ai bien l'impression qu'on est tous d'accord 😄 :

- sur la carte :
  - Vigilance verte 🟢 , Vigilance jaune 🟡 , Vigilance orange 🟠 , Vigilance rouge 🔴 
  - types de phénomène sur la période concernée
  - recommandation générale dans tous les cas de couleur de vigilance
  
- une vue détaillée en modale ouverte au clic sur un des phénomènes :
  - frise horaire du phénomène
  - recommandation particulière pour le phénomène si présent (orange, rouge)
 
@florianpanchout pas de collisions avec la gestion des [+] / [-] sur mobile ?

**Comment by florianpanchout** [comment]
Nope, je ne pense pas que ça pose de problème niveau UI.

J'ai modifié "Pas de vigilance" pour "Vigilance verte". L'idéal serait de pouvoir afficher le label que l'api me renvoie ("Vigilance météo: Jaune" pour l'instant).

**Comment by annepoirot** [comment]
Pour le moment on ne fait pas l'affichage détaillé, on le fera dans #173
