### ISSUE TITLE
Bug d'affichage en cas de plusieurs épisodes de pollution sur la tableau de bord

### ISSUE THREAD

**Issue by fcoufour** [betagouv/recosante#176]
Une alerte "épisode de pollution" est affichée même dans le cas où il s'agit juste d'un niveau d'Information (cas de Dôle le 16/01).

<img width="2496" alt="episode_pollution_information" src="https://user-images.githubusercontent.com/23194091/149973659-af0042fa-f55e-4e23-9100-6da6d0204d61.png">

A voir si c'est ce qui est souhaité et à affiner si besoin. L'API renvoie 3 niveaux : Pas de dépassement, Information et Alerte.

**Comment by florianpanchout** [comment]
Il me semble que c'est ce qui est souhaité : https://github.com/betagouv/recosante/issues/88#issuecomment-934220193

Les épisodes de pollution niveau alerte semblent très rares. Airparif n'en recense aucun en 2021 et 2022 (https://www.airparif.asso.fr/historique-des-episodes-de-pollution?year=2021#table-threshold-history)

**Comment by annepoirot** [comment]
Par contre il y a un bug sur l'affichage. A voir si c'est à corriger côté API ou côté front
