### ISSUE TITLE
Modifier le questionnaire avec les retours d'Agnès

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante#178]
Dans le questionnaire :
 * Mettre enfants **de moins de 6 ans**, et modifier la valeur à envoyer dans l’API par `moins_de_6ans`

Se reposer la question pour
 * Garder chauffage au bois et ajouter «insert»
 * Chaudière
 * Tout système de chauffage au fioul ou au gaz

**Comment by annepoirot** [comment]
Du coup deux choses à changer : 

1) Sur les enfants 
Modifier la partie sur les enfants pour ajouter la mention "moins de 6 ans". 
Donc ça devient **"Je renseigne si je vis avec des enfants de moins de 6 ans"**. Et modifier la valeur à envoyer dans l’API par moins_de_6ans

2) Sur le chauffage au bois 
- "cheminée ou poêle à bois" devient **"cheminée, insert ou poêle à bois"**
- "chaudière au fioul, au gaz ou électrique" devient **"chaudière au fioul ou au gaz"**
- "chauffage mobile d'appoint" devient **"chauffage mobile d'appoint au fioul"**

**Comment by fcoufour** [comment]
PR frontend : https://github.com/betagouv/recosante/pull/199
PR backend : https://github.com/betagouv/recosante-api/pull/378
