### ISSUE TITLE
Modifier le terme d'un pollen dans le mail et le dashboard

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#186]
Il faut que "Cypres" devienne "Cupressacées"

**Comment by fcoufour** [comment]
PR du site : https://github.com/betagouv/recosante/pull/188
PR de l'email : https://github.com/betagouv/recosante-mail/pull/93

Je fais la modification sur le prochain template qu'on utilisera pour le mail Indicateur : https://my.sendinblue.com/camp/template/1794/message-setup
