### ISSUE TITLE
Revoir le processus de désinscription

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#197]
- [x] Modifier le lien dans le mail "Modifier mes préférences ou me désinscrire" et mettre à la place ""Modifier mes préférences".
- Dans la page de profil utilisateur, lorsqu'on clique sur "supprimer mon compte" :
 * [x] ~~renvoyer vers la page de désinscription sendinblue => ce n'est pas possible~~
  * [x] modifier le texte du bouton pour mettre "supprimer mon compte" et non "profil"
- [x] ~~Dans la page de désinscription sendinblue, intégrer le questionnaire de désinscription. (Anne)~~

**Comment by annepoirot** [comment]
A faire : 
- Modifier le lien dans le mail "Modifier mes préférences ou me désinscrire" et mettre à la place ""Modifier mes préférences".
- Dans la page de profil utilisateur, lorsqu'on clique sur "supprimer mon compte" :
=> renvoyer vers la page de désinscription sendinblue
=> modifier le texte du bouton pour mettre "supprimer mon compte" et non "profil".

**Comment by annepoirot** [comment]
A faire : 
- Modifier le lien dans le mail "Modifier mes préférences ou me désinscrire" et mettre à la place ""Modifier mes préférences".
- Redemander côté sendinblue si on peut le retirer (et au pire envoyer mail au DPO)
- Faire le formulaire chez nous, sans champ libre (proposer de nous contacter si ils souhaitent en parler plus)

**Comment by annepoirot** [comment]
Anne rédige un message à SIB pour demander : 
- soit on passe pas par SIB => demander si on peut supprimer le lien
- soit on utilise leur page mais pour ça on a besoin qu'elle ne soit pas reliée à un compte => demander si on peut avoir un lien sans compte

**Comment by fcoufour** [comment]
- Modifier le lien dans le mail "Modifier mes préférences ou me désinscrire" et mettre à la place ""Modifier mes préférences". ✅

**Comment by fcoufour** [comment]
J'ai fait le choix de laisser le formulaire en l'état sur Nextcloud pour de raisons de facilité d'implémentation et d'usage et de ne modifier que la modale côté profil Recosanté :
<img width="695" alt="supprimer-mon-compte-apres" src="https://user-images.githubusercontent.com/23194091/187182801-8c3ca25b-e85d-4a29-a8ad-28bdc836a01e.png">

Avant :
<img width="834" alt="supprimer-mon-compte-avant" src="https://user-images.githubusercontent.com/23194091/187183059-6199b4ac-510b-43c4-a0d8-be7cc80df1d9.png">

OK avec ça ?

Il restera à :
- désactiver le contact SIB correspondant (à la volée ou dans une tâche récurrente) @l-vincent-l 
- mettre en cohérence ensemble tous les textes (messages sur le frontend, page de confirmation SIB, emails) en rapport avec la gestion de compte @annepoirot

**Comment by fcoufour** [comment]
J'ai fait un support pour avoir tous les éléments du parcours actuel à disposition : https://docs.google.com/presentation/d/1IazXCJyoL1fdXK9XQGiFcdHtPlfUwJe4g6zyIBpzEVw
