### ISSUE TITLE
[landings] Ajouter les logos des partenaires à la place des renvois vers legifrance etc

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#2]
Mettre en bas de page avec la phrase au dessus : Ils nous accompagnent 

Les logos sont tous sur le github ici : https://github.com/betagouv/ecosante/tree/main/ecosante/assets/images
J'ai rajouté celui des pollinarium sentinelles hier.

**Comment by florianpanchout** [comment]
Fait
