### ISSUE TITLE
Inclure les critères principaux des recommandations dans le catalogue

### ISSUE THREAD

**Issue by fcoufour** [betagouv/recosante#243]
https://pad.incubateur.net/vpGaiEa0R5GZ_3xNIqh8rQ

**Comment by annepoirot** [comment]
Je m'occupe de modifier les catégories pour l'indice ATMO entre QAI et et QAE dans l'admin des recos. 

Indice ATMO : 
- Bon à Moyen : 
   Qualité de l'air intérieur : 
   Qualité de l'air extérieur : 
- Dégradé à extrêmement mauvais
