### ISSUE TITLE
Créer une page pour le referal médecins

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#25]
- Nom de l'URL : http://recosante.beta.gouv.fr/inscription-patients

- Sur la landing médecins, dans la partie "comment ça marche", ajouter un bouton "Inscrire vos patients" qui renvoie vers cette page. 

- L'objectif est d'avoir une page sur laquelle un médecin peut remplir son nom, son adresse mail, et l'adresse mail de son ou ses patients (leur donner la possibilité de rentrer plusieurs adresses).

- Contenu de la page ici : https://pad.incubateur.net/hdzp_79_RcujiK8pRZ-WxA 

- Une fois que le médecin a cliqué sur "Inscrire un·e patient·e" => page de confirmation + possibilité d'inscrire un autre patient via un lien "Inscrire un·e autre patient·e".

**Comment by florianpanchout** [comment]
Est ce que ce n'est pas un peu lourd de demander nom et prénom des patients en plus du mail ? S'il veut en mettre 10 d'un coup ça peut vite compliquer ses copier coller.

**Comment by annepoirot** [comment]
Ah yes partons sur un champ simple où on peut séparer par des virgules les adresses mails !

**Comment by florianpanchout** [comment]
C'est fait (https://recosante.beta.gouv.fr/inscription-patients/).

On passe par Sendinblue pour l'envoi du mail. Le template est ici : 
https://my.sendinblue.com/camp/template/487/message-setup

J'ai enlevé le champ mail pour le médecin vu qu'on ne l'utilise nul part.
