### ISSUE TITLE
Rendre possible le partage de Recosanté entre usagers (referal)

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#26]
L'objectif est de permettre aux usagers de partager Recosanté à un proche via sms, mail et réseaux sociaux : 
- mail
- sms
- whatsapp
- messenger

Cette option serait disponible à la fin de l'inscription et sur la landing page usagers. 

Le texte pré-remplit : 

Tu connais Recosanté ? C'est une lettre d'information quotidienne qui te donne des conseils personnalisés en fonction de tes habitudes pour te protéger des impacts de la qualité de l’air sur ta santé. Tous les matins, tu reçois un mail qui t'informe de la qualité de l'air autour de chez toi et une recommandation pour adapter ton comportement et/ou tes activités en fonction.
Pour t'inscrire : http://recosante.beta.gouv.fr/

**Comment by florianpanchout** [comment]
C'est fait sauf pour le partage par sms.

Il faudrait passer par Sendinblue. Ça me semble complexe (et possiblement couteux) pour peu de chose.

**Comment by annepoirot** [comment]
OK ça me convient !

**Comment by annepoirot** [comment]
Deux bug que j'ai noté : 
- Messenger ne fonctionne pas 
- le mail s'envoie par défaut à ton adresse

**Comment by florianpanchout** [comment]
My bad. C'est corrigé
