### ISSUE TITLE
Landing médecins : pouvoir télécharger le kit de communication à la place du flyer

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#38]
Sur le bouton "télécharger le flyer" => changer par "Télécharger le kit de communication" 

Et cela permet de télécharger ce dossier 
[Recosanté_Kit communication professionnel de santé.zip](https://github.com/betagouv/recosante/files/6263657/Recosante_Kit.communication.professionnel.de.sante.zip)

**Comment by florianpanchout** [comment]
Done
