### ISSUE TITLE
[landing usagers] temps d'apparition du mockup un peu long

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#4]
Un détail, mais si on peut le faire apparaître un peu plus rapidement c'est top !

**Comment by florianpanchout** [comment]
@annepoirot C'est le délai avant l'apparition qui est trop long ? (il est basé sur la positon de scroll). Ou la durée de l'animation ?

**Comment by annepoirot** [comment]
Le délai d'apparition plutôt je dirais !

**Comment by florianpanchout** [comment]
Fait
