### ISSUE TITLE
Créer une page "données personnelles et cookies"

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#41]
# Suivi des audiences et données personnelles

## Données personnelles

Les données collectées ont exclusivement pour but de personnaliser les recommandations envoyées. Elles ne sont accessibles que par l’équipe Recosanté et les services que l'équipe utilise.

Conformément à la réglementation en matière de données personnelles, vous disposez d'un droit d'accès, de rectification, d'opposition, d'effacement et de portabilité de vos données que vous pouvez exercer par courrier électronique à l'adresse : contact@recosante.beta.gouv.fr

## Cookies

Ce site dépose un petit fichier texte (un « cookie ») sur votre ordinateur lorsque vous le consultez. Cela nous permet de mesurer le nombre de visites et de comprendre quelles sont les pages les plus consultées.

Nous n'affichons pas de banière de consentement aux cookies car nos outils de suivi d'audience sont correctement configurés pour respecter la vie privée des utilisateurs. Selon la loi, notre site internet est donc exempté d’autorisation préalable.

L'outil que nous utilisons est [Matomo](https://matomo.org/), un outil libre, paramétré pour être en conformité avec la recommandation « Cookies » de la CNIL. Cela signifie que votre adresse IP, par exemple, est anonymisée avant d’être enregistrée. Il est donc impossible d’associer les visites sur ce site à une personne.

Les statistiques d’usage sont disponibles en accès libre [ici](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=157&updated=1#?idSite=157&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1)

## Crédit photo

[Freepik](https://freepik.com)

**Comment by florianpanchout** [comment]
C'est fait : https://recosante.beta.gouv.fr/cookies
