### ISSUE TITLE
Améliorer la vitesse d'affichage sur mobile pour le SEO/ads

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#47]

**Comment by chaibax** [comment]
Aujourd'hui : 

![Capture d’écran 2021-04-14 à 17 49 14](https://user-images.githubusercontent.com/3593868/114740017-bc2a6300-9d49-11eb-93b8-f7e0a64078d9.png)

Source : https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Frecosante.beta.gouv.fr%2F

**Comment by florianpanchout** [comment]
On oscille maintenant entre 75 et 85. Je pourrai difficilement monter au dessus en continuant d'utiliser un framework

**Comment by chaibax** [comment]
On a gagné plusieurs points, ça me va! 
Merci

**Comment by florianpanchout** [comment]
98/100 sur la nouvelle version (en staging)

https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=https%3A%2F%2Frecosante.cleverapps.io%2F
