### ISSUE TITLE
Faire passer la page d'avis sur les recos sur le nouveau site 

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#48]
Il s'agit des deux pages liées à la question "Allez vous appliquer cette recommandation" => il faudrait les rendre disponibles sur le nouveau site. 
@l-vincent-l est-ce que @florianpanchout aura besoin de quelque chose côté back ?

**Comment by annepoirot** [comment]
<img width="1399" alt="Capture d’écran 2021-04-22 à 10 44 08" src="https://user-images.githubusercontent.com/63290799/115684531-b9d29500-a357-11eb-9eca-83899c146a28.png">
Page avis = oui

**Comment by annepoirot** [comment]
![Uploading Capture d’écran 2021-04-22 à 10.44.23.png…]()
Page avis = non

**Comment by l-vincent-l** [comment]
Une API a été mise en place.
C’est possible de l’appeler avec 
`POST /newsletter/short_id/avis/?applique=(oui,non)`
Il est possible d’envoyer un commentaire en envoyant dans le corps de la requête:
```json
{
  "avis": "Mon avis est important"
}
```
Dans les headers il faut mettre : 
```
Accept: application/json
Content-Type: application/json
```
Le `Content-Type` est à mettre que s’il y a un corps

**Comment by florianpanchout** [comment]
@l-vincent-l 
https://ecosante.beta.gouv.fr/newsletter/EkY6q9t8/avis/?appliquee=oui me retourne une 404. https://ecosante.beta.gouv.fr/newsletter/EkY6q9t8/avis?appliquee=oui me retourne du html

**Comment by l-vincent-l** [comment]
Ah désolé pour le trailing_slash qui ne redirige pas.

C’est normal que sans le trailing dans un navigateur cela renvoie du HTML, à la base c’était fait pour parler avec un navigateur et donc renvoyer du HTML.
Quand tu l’appelles comme une API il faut ajouter le header `Accept: application/json` comme dans cette requête curl
```
curl -H "Accept: application/json" https://ecosante.beta.gouv.fr/newsletter/EkY6q9t8/avis\?appliquee\=oui                                                                                               ```

**Comment by florianpanchout** [comment]
Arf, je declarais aussi le Content-Type, ce qui renvoie une 400 sans body.

C'est en ligne (https://recosante.beta.gouv.fr/avis/?short_id=EkY6q9t8&avis=non) et intégré au prochain template de newsletter
