### ISSUE TITLE
[questionnaire] remplacer les codes INSEE par les codes postaux

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#5]

**Comment by florianpanchout** [comment]
@l-vincent-l Est ce que c'est possible pour l'api de me renvoyer le code postal et le nom de la ville en plus du code insee ?

**Comment by l-vincent-l** [comment]
ouais, l’api geo te permet de faire ça

**Comment by l-vincent-l** [comment]
https://api.gouv.fr/documentation/api-geo

**Comment by florianpanchout** [comment]
C'est ce que j'ai fait. Mais vu que tu as le nom de la ville (pour Sendinblue) je me suis dit que tu avais peut être ces infos en base

**Comment by l-vincent-l** [comment]
Ah, dans le retour de l’API, oui je dois pouvoir faire ça, je pensais qu’on parlait du champ de recherche

**Comment by l-vincent-l** [comment]
J’ai ajouté les champs `ville_nom` et `ville_codes_postaux` en réponse de l’API

**Comment by florianpanchout** [comment]
Done. 

Par contre les valeurs ville_nom  et ville_codes_postaux ne se mettent pas à jour après initialisation @l-vincent-l

**Comment by l-vincent-l** [comment]
Tu ne peux pas setter les valeurs, par contre elles se mettent à jour une fois l’INSEE remplit.

**Comment by florianpanchout** [comment]
Oui c'est ce que je dis : Elles ne se mettent pas à jour après la première initialisation

**Comment by l-vincent-l** [comment]
Ok, c’est fixé.
Je pense que sans trop se tromper tu peux trier par alphanumérique croissant les codes postaux, le premier en 000 sera le plus compris.

**Comment by florianpanchout** [comment]
Il n'y a pas les 000 (en tout cas pas pour Paris, je n'ai pas checké les villages). Du coup j'en affiche juste 2 puis "..."
