### ISSUE TITLE
Créer une page /politiquedeconfidentialité

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#57]
Cette page s'ouvre lorsque l'utilisateur clique sur "données personnelles" en pied de page.  

Contenu : 

### Responsable de traitement

La Direction générale de la santé (DGS) et la Direction générale de la prévention des risques (DGPR) sont les responsables du traitement de vos données à caractère personnel.

Les coordonnées de la DGS sont : 
Direction générale de la Santé
Sous direction prévention des risques liés à l'environnement et à l'alimentation
14, avenue Duquesne
75350 PARIS 07 SP

Les coordonnées de la DGPR sont :
Direction générale de la prévention des risques
Tour Séquoia
92055 La Défense Cedex

La Direction Interministérielle du Numérique (DINUM) assure, pour le compte de la DGS et de la DGPR, la supervision de l’équipe produit (produit « Recosanté » conçu selon l'approche Startup d’Etat dans le cadre du programme beta.gouv.fr) qui gère et déploie le service. Les sociétés CleverCloud (hébergeur), Scopyleft, Google Adwords et Sendinblue interviennent également en tant que sous-traitants.

### Données collectées

Les données personnelles traitées sont : 
- Identification : adresse mail, commune de résidence
- Inscription à la lettre d'information : 
    - Activités : sport, ménage, bricolage, jardinage.
    - Mode de déplacement : vélo, voiture, transports en commun.
    - Préférences de réception : informations sur le risque allergique pollen et sur la pollution de l'air.
    - Autres informations : type de chauffage, animaux de compagnie, présence d'enfants dans le logement.

A noter : les données sont collectées sur un mode binaire (case cochée ou non) et non détaillées selon la personne. Aucun justificatif n’est collecté ni stocké sur la plateforme.

Les données collectées lors de l’inscription sont utilisées exclusivement pour envoyer les informations souhaitées par l'utilisateur. 

### Base légale du traitement

La base légale du traitement est l'exercice d'une mission d'intérêt public, basée sur l'article L. 1411-1 du Code de la santé publique qui dispose que la politique de santé relève de la responsabilité de l’Etat et comprend la promotion de la santé dans tous les milieux de vie ainsi que la prévention collective et individuelle tout au long de la vie.

### Finalités du traitement 

La finalité du traitement de données réalisé par Recosanté est de **transmettre des informations et recommandations  aux utilisateurs pour les aider à se protéger des impacts environnementaux sur leur santé.**

### Durée de conservation des données

Les données collectées sont supprimées dès lors que l'utilisateur se désinscrit de la lettre d'information. 

### Sécurité et confidentialité
Les données personnelles sont traitées dans des conditions sécurisées, selon les moyens actuels de la technique, dans le respect des dispositions relatives à la protection de la vie privée et notamment au référentiel général de sécurité, prévu à l’article 9 de l’ordonnance 2005-1516 du 8 décembre 2005 relative aux échanges électroniques entre les usagers et les autorités administratives et entre les autorités administratives.

Les moyens de sécurisation suivants ont notamment été mis en œuvre :
#### Contrôle d’accès
La base de données des utilisateurs n’est accessible qu’aux seuls membres de l’administration du service

#### Mesures de traçabilité
Les logs applicatifs permettent de savoir qui a eu accès à cette base de données.

#### Mesures de protection des logiciels
Les mises à jour et les mesures de protection sont assurées par l'hébergeur CleverCloud.

#### Sauvegarde des données
Les sauvegardes sont assurées par l'hébergeur CleverCloud.

#### Chiffrement des données
Site uniquement accessible en HTTPS.

### Sous-traitants
Certaines des données sont envoyées à des sous-traitants pour réaliser certaines missions. Recosanté s’est assuré de la mise en œuvre par ses sous-traitants de garanties adéquates et du respect de conditions strictes de confidentialité, d’usage et de protection des données.

**Partenaire** : Sendinblue
**Pays destinataire** : France	
**Traitement réalisé** : envoi des lettres d'information aux utilisateurs
**Garanties** : https://fr.sendinblue.com/legal/privacypolicy/

**Partenaire** : CleverCloud
**Pays destinataire** : France	
**Traitement réalisé** : hébergement du site	
**Garanties** : https://www.clever-cloud.com/en/privacy-policy

**Partenaire** : Google Adwords
**Pays destinataire** : Etats-Unis	
**Traitement réalisé** : réalisation de publicité en ligne
**Garanties** : https://privacy.google.com/intl/fr_fr/businesses/compliance/

**Partenaire** : Scopyleft
**Pays destinataire** : France
**Traitement réalisé** : accès aux infrastructures de production pour leur gestion et leur administration ;  accès et consultation des données de production pour analyser et corriger d’éventuelles anomalies ou évolutions demandées par les responsables de traitement
**Garanties** : supports contractuels liés au marché public de la DINUM pour le développement et le design de services publics numériques en mode agile

### Droits des personnes

Vous disposez des droits suivants concernant vos données à caractère personnel :
- Droit d’information, d’accès et de communication des données ;
- Droit de rectification des données ;
- Droit d'opposition.

Pour toute demande, vous pouvez écrire un email à l’équipe Recosanté : contact@recosante.beta.gouv.fr

Si vous estimez, après nous avoir contactés, que vos droits ne sont pas respectés ou que le traitement n’est pas conforme à la réglementation sur la protection des données à caractère personnel, vous pouvez adresser une réclamation à la CNIL.

**Comment by florianpanchout** [comment]
C'est fait : https://recosante.beta.gouv.fr/politiquedeconfidentialite
