### ISSUE TITLE
[données d'outre mer] mettre un message d'erreur lorsque les personnes s'inscrivent pour Mayotte, Guyane, Réunion, Nouvelle Calédonie.

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante#58]
J’ai ajouté un point d’entrée qui permet de déterminer sur une ville est disponible ou non sur Recosanté.
Il est disponible ici : https://ecosante.beta.gouv.fr/city-availability
Il s’appelle avec un paramètre `insee` dans lequel on met le code INSEE d’une ville.

Exemple d’appel
```bash
curl http://ecosante.beta.gouv.fr/city-availability?insee=97416
```
Retour : 
```json
{"availability":false}
```
Ici la ville n’est pas disponible alors que dans cet appel
```bash
curl http://ecosante.beta.gouv.fr/city-availability?insee=75056
```
Retour:
```json
{"availability":true}
```
La ville est disponible !

Je ne sais pas très bien à quelle étape intégrer ce check, je suis disponible pour en parler

**Comment by florianpanchout** [comment]
J'ai mis un message d'alerte au moment ou l'on choisi la ville. On ne peut pas valider et passer à la suite si la ville n'est pas disponible
