### ISSUE TITLE
Créer une page "Ils parlent de nous"

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#59]
Mettre le lien dans le footer.

L'idée c'est de rajouter des logo d'associations ou de partenaires. Je me dis que le mieux serait que je puisse etre autonome sur l'ajout, si tu as une idée de comment je pourrais faire ça :)

**Comment by florianpanchout** [comment]
Il y a juste une image (plus lien) par partenaire ?

**Comment by annepoirot** [comment]
Ah oui idéalement image et lien exact

**Comment by florianpanchout** [comment]
C'est fait  :  https://recosante.beta.gouv.fr/partenaires

Le contenu est ici : https://github.com/betagouv/recosante/blob/master/content/texts/partenaires.md
