### ISSUE TITLE
[widget] Modifier les couleurs des polluants/pollens

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#60]
Il faudrait modifier les couleurs de l'affichage des indicateurs environnementaux sur le widget pour la présentation du comité. La manière dont c'est affiché actuellement peut porter à confusion et je crains que ça ne retienne l'attention de certaines personnes expertes et qu'on passe du temps là dessus pour rien haha.

En gros la logique c'est qu'il faut que la couleur de l'indice soit la même que le polluants ou pollens le plus présents dans l'air

Idéalement je mettrais bien :
- Indice ATMO dégradé et PM10 dégradé, et tous les autres polluants en moyen
- RAEP élevé avec  les graminées en élevé et les autres pollens entre faible à moyen 

Merci !

**Comment by florianpanchout** [comment]
C'est fait

L'indice ATMO est l'indice réel (c'est la seule donnée que je reçois). Du coup j'ai calqué la valeur des PM10 dessus
