### ISSUE TITLE
[widget] L'objectif et la reco ne correspondent pas

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#61]
<img width="498" alt="Capture d’écran 2021-05-31 à 10 35 05" src="https://user-images.githubusercontent.com/63290799/120165701-1f8a2a80-c1fc-11eb-868f-9a322f150936.png">
Il s'agit d'une reco sur la qualité de l'air intérieur

**Comment by florianpanchout** [comment]
C'est corrigé (les recommandations aussi sont statiques pour l'instant)
