### ISSUE TITLE
Modifier la page "ils parlent de nous"

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#64]
1) Changer le nom de la page par "Partenaires" 

En dessous on aurait les logos de : Atmo, RNSA, pollinarium, Santé respiratoire France

2) Ajouter une catégorie en dessous "Ils parlent de nous"

En dessous il y aurait les logos de : FFAIR, SPLF, mag de la santé

**Comment by florianpanchout** [comment]
Done
