### ISSUE TITLE
Supprimer le tracking Lumiere

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#66]
@florianpanchout est-ce qu'on supprime Lumiere suite au retour d'Ishan sur mattermost ?

**Comment by florianpanchout** [comment]
@goffle Pourquoi le tracking disparait ? Vous n'êtes pas RGPD compliant ? Ou c'est le côté pas open source qui déplait ?

**Comment by florianpanchout** [comment]
Fait via https://github.com/betagouv/recosante/pull/65
