### ISSUE TITLE
Permettre de build le dashboard sur Clever Cloud

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante#71]
Clever Cloud plante au moment du build lorsque l'on essaie de générer toutes les pages villes ( > 3000). Et ce, peu importe le dimensionnement de l'instance de build. Si tu as une idée...

**Comment by annepoirot** [comment]
Si jamais ça ne fonctionne pas sur Clever Cloud on pourra le laisser sur netlify

**Comment by florianpanchout** [comment]
Le site est maintenant hébergé sur Gatsby Cloud. Il faudra probablement prendre l'abonnement à $20 / mois. 

On a gagné 5 points sur PageSpeed au passage
