### ISSUE TITLE
[questionnaire] ajouter une question "Je vis avec des enfants" oui/non

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#8]

**Comment by florianpanchout** [comment]
@l-vincent-l du coup il faut aussi la propriété dans l'api

**Comment by annepoirot** [comment]
Normalement il y est déjà car on posait la question avant mais j'ai oublié de la rajouter dans le nouveau questionnaire. Tu confirmes @l-vincent-l ?

**Comment by florianpanchout** [comment]
@l-vincent-l Possible que la valeur enfant soit dans un tableau (comme pour les autres propriétés) ?

**Comment by florianpanchout** [comment]
@annepoirot C'est en ligne

**Comment by annepoirot** [comment]
J'ai un bad resquest à partir de la question sur le chauffage de mon côté

**Comment by florianpanchout** [comment]
Tu as vidé ton cache ? Si oui tu réponds quoi à cette question pour que ça plante ?

(L'api plante lorsque l'on répond "aucun" à la question déplacement, Vincent est en train de regarder)

**Comment by l-vincent-l** [comment]
Dans mes tests je n’ai plus ce problème
