### ISSUE TITLE
Designer les maquettes pour météo France

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#82]
J'ai eu un retour de météo france concernant la proposition de maquette que je leur avais envoyée avec indice UV et vigilance météo. 

Leur message : 

Nous avons une grande réticence sur la manière de traiter la vigilance météo dans votre maquette. En effet, celle-ci est fortement cadrée par une circulaire interministérielle et nous pensons qu'en modifier les pictogrammes ou les termes peut être déstabilisant pour l'utilisateur, voir l'induire en erreur. Sur le sujet, nous pensons indispensable qu'il y ait une harmonisation des vecteurs d'information publique. Vous trouverez toutes les infos utiles sur notre site vigilance : https://vigilance.meteofrance.fr/fr/guide-vigilance-meteo 

Concernant les pictos
Nous préférons que vous repreniez  ceux utilisés sur les cartes de vigilance ou sur le site https://vigilance.meteofrance.fr/fr. D'autre part, il ne faut surtout pas fusionner les pictos (comme sur l'exemple que vous nous avez transmis).

Concernant les termes
Nous souhaitons que vous utilisiez ceux qui sont prévus dans la circulaire (et pas "élevée" ou "maximal"par exemple). Pour info, voici les niveaux de vigilances prévus :

Vigilance rouge : Une vigilance absolue s'impose. Des phénomènes dangereux d'intensité exceptionnelle sont prévus. Tenez-vous régulièrement au courant de l'évolution de la situation et respectez impérativement les consignes de sécurité émises par les pouvoirs publics.
Vigilance orange : Soyez très vigilant. Des phénomènes dangereux sont prévus. Tenez-vous au courant de l'évolution de la situation et suivez les conseils de sécurité émis par les pouvoirs publics.
Vigilance jaune : Soyez attentifs. Si vous pratiquez des activités sensibles au risque météorologique ou exposées aux crues, des phénomènes habituels dans la région mais occasionnellement et localement dangereux (ex. mistral, orage d'été, montée des eaux ) sont en effet prévus. Tenez-vous au courant de l'évolution de la situation.
Vigilance verte : Pas de vigilance particulière.

D'autre part, la vigilance météo va évoluer dans les prochains mois en affichant deux séries de pictos (un pour le jour J et un pour J+1) à chaque diffusion.

**Comment by annepoirot** [comment]
<img width="309" alt="Capture d’écran 2021-09-20 à 11 38 48" src="https://user-images.githubusercontent.com/63290799/133982640-8825edf3-460e-45fe-b62d-304055c06bbc.png">
(je suis en attente de leur retour pour valider qu'on peut partir sur ces pictogramme comme base)

**Comment by florianpanchout** [comment]
Si on remplace les carrés de couleurs par les pictos, et que l'ont trouve un visuel plus généraliste pour l'ensemble de l'indicateur, ça passe non ?

**Comment by florianpanchout** [comment]
J'ai modifié le picto : 

https://www.figma.com/proto/gxHNi1hXW27dxgc4kaP4NN/Recosanté?page-id=1807%3A0&node-id=1903%3A0&viewport=324%2C48%2C1&scaling=min-zoom

Je peux difficilement faire plus généraliste.

Pour les pictos de chaque phénomène, il me faudrait des versions svg de leur picto s'ils veulent que je puisse utiliser les mêmes. 

Et pour les termes : Est ce qu'on est sur de vouloir se plier à leur demande ? 
- On ajoute encore de nouveaux termes pour l'utilisateur, qui ont encore moins de sens que ceux d'ATMO
- On connait déjà la couleur de la vigilance grâce au picto
- Ils ne la respecte pas eux même (https://vigilance.meteofrance.fr/fr)

**Comment by florianpanchout** [comment]
(j'ai commencé à traiter ce ticket pour pouvoir avoir le picto "Vigilance météorologique" final, pour que l'on puisse avoir des visuels de com prêts. Le reste peut attendre)

**Comment by florianpanchout** [comment]
![Screenshot 2021-10-01 at 18 21 40](https://user-images.githubusercontent.com/8115933/135707418-3ca2d48e-bef1-4e6c-bb28-c3cf66711622.png)

**Comment by annepoirot** [comment]
Par contre avec cette proposition là comment on affiche l'absence de vigilance en vert dans le picto ?

**Comment by florianpanchout** [comment]
Comme pour le raep, avec les 3 nuages en bleu clair ?

**Comment by annepoirot** [comment]
Du coup on mettrait pas de vert ? Je pense qu'ils s'attendent à ça, mais on pourra le défendre au pire

**Comment by florianpanchout** [comment]
C'est plus cohérent avec nos autres picto de faire comme ça. Je pense qu'ils s'en fichent de ce niveau de vigilance (qui correspond à "pas de vigilance"), comparé aux autres.
