### ISSUE TITLE
Supprimer l'optin pour l'inscription

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante#83]
Actuellement on a une checkbox : "J'accepte de recevoir des emails de la part de Recosanté (pas de publicité)"

Cette checkbox n'est plus nécéssaire (ni obligatoire, ni utile) dans notre nouveau process d'inscription (l'utilisateur sait exactement ce qu'il va recevoir à l'étape ou il rentre son email).

Je propose donc de la supprimer dans cette nouvelle version

**Comment by annepoirot** [comment]
Si on est certain qu'elle n'est plus obligatoire ça me convient !

**Comment by florianpanchout** [comment]
Sur et certain. Je suis un expert sur le sujet maintenant que j'ai fait la présentation d'1h d'Octo !
