### ISSUE TITLE
Afficher les épisodes de pollution sur le dashboard

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante#88]
Est-ce que tu l'avais déjà en tête ?

**Comment by florianpanchout** [comment]
Je repose la même question qu'ici : https://github.com/betagouv/recosante-api/issues/273#issuecomment-933416760

Qu'est ce qui définit un épisode de pollution ? Est il lié à l'indice ATMO ?

**Comment by annepoirot** [comment]
Un épisode de pollution est déclaré quand les concentrations de certains polluants dépassent des seuils définis dans la loi. 
<img width="857" alt="Capture d’écran 2021-10-05 à 10 52 52" src="https://user-images.githubusercontent.com/63290799/135992016-a5eb038d-01be-4205-96ec-3b96b05cfed0.png">

Comparaison avec le nouvel indice ATMO :
<img width="1041" alt="Capture d’écran 2021-10-05 à 11 05 40" src="https://user-images.githubusercontent.com/63290799/135994888-e1ca7fae-552e-4cd5-a7dd-343b4acee5cf.png">
Avec l'ancien indice ATMO, les seuils de concentration étaient alignés avec les épisodes de pollution. Or avec le nouvel indice, déjà ils ont rajouté les PM2.5 qui ne sont pas dans les épisodes de pollution + ils ont baissé les seuils. Donc ya une dissonance entre les seuils des deux mesures. En gros le Bureau de la Qualité de l'Air souhaiterait que ces seuils soient alignés => et dans ce cas on aurait plus d'épisodes de pollution au seuil d'information. 


En gros je dirais pour résumer que les deux mesures sont liées car basées sur la concentration en polluants. Mais les seuils définis ne sont pas les mêmes. L'indice ATMO est un indice pour faire de la communication et de la sensibilisation au sujet quand les épisodes de pollution sont un procédure sanitaire réglementée et obligatoire.

**Comment by annepoirot** [comment]
Si jamais c'est pas clair (car je me rend compte que c'est quand même compliqué à expliquer), on peut se prendre 15min pour en discuter avec @MarinePurson aussi

**Comment by florianpanchout** [comment]
L'épisode de pollution c'est la colonne "Niveau d'information et de recommandation" ou "Niveau d'alerte" ?

**Comment by annepoirot** [comment]
Les deux ! Il y a en gros deux niveaux d'épisode de pollution.

Niveau d'information et de recommandation : Niveau au-delà duquel une exposition de courte durée présente un risque pour la santé humaine de groupes particulièrement sensibles au sein de la population. Ce niveau rend nécessaire l'émission d'informations immédiates et adéquates à destination de ces groupes, et des recommandations pour réduire certaines émissions.

Niveau d'alerte : niveau au-delà duquel une exposition de courte durée présente un risque pour la santé de l'ensemble de la population ou un risque pour la dégradation de l'environnement, justifiant l'intervention de mesures d'urgence. 
Le niveau d'alerte sur persistance est déclenché lorsque le niveau d'information et recommandation est prévu pour le jour même et le lendemain.

La procédure est déclenchée de fait pour un polluant sur constat de dépassement du seuil correspondant ou à partir de la prévision d’un risque de dépassement émis par Airparif.

**Comment by florianpanchout** [comment]
Ça marche. Et qu'est ce qui caractérise un épisode de pollution (qu'est ce qu'on veut afficher). Le polluant en question et c'est tout ?

**Comment by annepoirot** [comment]
Pour moi on voudrait peut-être afficher le seuil (information ou alerte) et le polluant. Dans les données @l-vincent-l il y a toujours écris le seuil ?

**Comment by annepoirot** [comment]
Et aussi pour les recommandations sanitaires associées, se pose la question de comment on les affiche. Vu qu'on se saura plus si une personne est sensible ou pas, on sera obligé de toutes les afficher. 
Voilà le tableau des recommandations en fonction des populations et des polluants :
https://solidarites-sante.gouv.fr/sante-et-environnement/air-exterieur/qualite-de-l-air-exterieur-10984/article/recommandations-en-cas-d-episode-de-pollution

**Comment by l-vincent-l** [comment]
Il y a une première version en ligne.

La documentation est comme d’habitude accessible ici https://api.recosante.beta.gouv.fr/v1/swagger/ui

À la racine il y a dans level le niveau maximum (qui peut être recommandation ou alerte)
Dans label un résumé des labels qu’il y a dans les sous-indices.

**Comment by florianpanchout** [comment]
Merci ! Possible de renvoyer un épisode de pollution en staging pour tester ?

**Comment by l-vincent-l** [comment]
Je viens d’ajouter un paramètre `date` à l’API

Et en plus, miracle ! demain il y a un épisode de pollution à Paris ! Bénis soient le diesel et les autres particules fines !

Un exemple d’appel : http://api.recosante.beta.gouv.fr/v1/?insee=75056&date=2021-11-10

**Comment by florianpanchout** [comment]
Ça tombe bien ça !

Pour les labels, est ce que ce ne serait pas mieux de reprendre les labels de l'indice ATMO : O3, NO2, PM10 ?

Et je n'ai pas `validity` ni `source` dans l'objet `episodes_pollution`. Ce n'est pas forcement les mêmes que l'indice ATMO si j'ai bien compris

**Comment by florianpanchout** [comment]
(@annepoirot C'est normal que l'on ai différentes recommandations qui ne disent pas exactement la même chose mais presque ? On a pas une obligation d'affichage en cas d'épisode de pollution ?)

**Comment by MarinePurson** [comment]
- Pour les recos, il y a des recos spécifiques obligatoires en cas d'épisode de pollution : https://solidarites-sante.gouv.fr/sante-et-environnement/air-exterieur/qualite-de-l-air-exterieur-10984/article/recommandations-en-cas-d-episode-de-pollution 
A voir comment vous aviez synthétisé avec @annepoirot 

- Dans la version en staging, il y a écrit "aux : particules_fines" : il faudrait supprimer les deux points et le tiret du bas.

- Pour moi, pas besoin de mettre le seuil pour chaque polluant (d'autant plus qu'à ce stade, on ne les explicite nul part).

**Comment by florianpanchout** [comment]
> Dans la version en staging, il y a écrit "aux : particules_fines" : il faudrait supprimer les deux points et le tiret du bas.

En lien avec https://github.com/betagouv/recosante/issues/88#issuecomment-964353750 : est ce que ce ne serait pas même mieux de mettre "PM10" pour être cohérent avec le reste du site ?

**Comment by annepoirot** [comment]
- Je n'ai pas de préférence entre particules fines et PM10. Mais si on met PM10 dans la pop up, est-ce qu'il ne faudrait pas mettre une définition ? 

- Pour les recommandations : effectivement on a des recommandations réglementées qui normalement sont déjà dans notre catalogue de reco. 
Pour PM10, NO2 et SO2 c'est :
* En cas de gêne respiratoire ou cardiaque, prendre conseil auprès d’un professionnel de santé. * Privilégier des sorties plus brèves et celles qui demandent le moins d’effort. * Réduire, voire reporter, les activités physiques et sportives intenses (dont les compétitions). Si vous êtes une personne sensible ou vulnérable : * prendre conseil auprès de votre médecin pour savoir si votre traitement médical doit être adapté le cas échéant ; * éviter les zones à fort trafic routier, aux périodes de pointe ; * privilégier les activités modérées.

Pour O3 c'est:
* En cas de gêne respiratoire ou cardiaque, prendre conseil auprès d’un professionnel de santé. * Privilégier des sorties plus brèves et celles qui demandent le moins d’effort. * Maintenir les activités physiques et sportives intenses (dont les compétitions) à l’intérieur. Si vous êtes une personne sensible ou vulnérable : * prendre conseil auprès de votre médecin pour savoir si votre traitement médical doit être adapté le cas échéant ; * éviter les sorties durant l’après-midi lorsque l’ensoleillement est maximum ; * éviter les activités physiques et sportives intenses (dont les compétitions) en plein air ; celles peu intenses à l’intérieur peuvent être maintenues.

- Pour l'affichage : Je pense que c'est bien de garder le pop up quand on arrive sur le site mais il faut que l'information reste accessible sur le dashboard une fois la fenêtre fermée. En fait pour la qualité de l'air, il faudrait que l'information liée à un épisode de pollution surpasse l'information liée à l'indice ATMO.  
Peut-être qu'on peut avoir dans l'encadré qualité de l'air en première une phrase sur fond rouge (comme dans le mail) "Un épisode de pollution aux PM10 est prévu aujourd'hui". En dessous, les recommandations. Et en dessous l'indice de qualité de l'air sans recommandation ? Qu'en pensez-vous @MarinePurson @mariegasnier1 ?

**Comment by mariegasnier1** [comment]
Par exemple, on peut mettre dans le popup "PM10 (particules fines)" ? Mais pour un souci de cohérence, je garderais les recommandations sous l'indicateur

**Comment by florianpanchout** [comment]
J'ai ajouté un affichage permanent sur le dashboard (toujours sur le staging : https://recosantestaging.gatsbyjs.io/place/75056/paris/)

Il reste : 
- [ ] Ajouter `validity` et `source` dans l'objet `episodes_pollution` 
- [ ] Enlever les : dans le titre
- [ ] Modifier `particules_fines` pour `PM10 (particules fines)` (et pareil pour les autres labels)

**Comment by mariegasnier1** [comment]
Vraiment top ! Merci

**Comment by l-vincent-l** [comment]
@florianpanchout j’ai fini d’ajouter les derniers points

**Comment by florianpanchout** [comment]
Cool merci ! Est ce qu'il y a moyen de tester sur le staging, ou je passe directement en prod et on voit au prochain épisode de pollution ?

**Comment by l-vincent-l** [comment]
Tu peux tester en mettant une date en particulier, par exemple le 10 novembre à  Paris

**Comment by florianpanchout** [comment]
Il reste les `:` dans le label. Sinon tout me semble bon, je passe le front en prod.

**Comment by l-vincent-l** [comment]
Les deux points sont enlevés

**Comment by florianpanchout** [comment]
L'api ne renvoie pas d'épisode de pollution pour Paris aujourd'hui, alors qu'il y en a un en cours selon Airparif. Les indices des polluants ne sont pas bon non plus

**Comment by fcoufour** [comment]
Pour le 15/01 à Paris, l'API renvoyait ceci (effectivement pas d'épisode de pollution) :
```
	"episodes_pollution": {
		"advice": null,
		"indice": {
			"details": [],
			"label": "",
			"level": ""
		},
		"sources": [],
		"validity": {
			"area": null,
			"end": null,
			"start": null
		}
	},
	"indice_atmo": {
		"advice": {
			"details": "<p>\ud83d\udca1Dans une \u00e9tude r\u00e9alis\u00e9e en 2015, l\u2019observatoire r\u00e9gional de surveillance de\nla qualit\u00e9 de l\u2019air en Occitanie a d\u00e9montr\u00e9 que le choix d'emprunter un axe\navec peu de trafic routier a permis de r\u00e9duire l'exposition moyenne du\ncycliste ou du pi\u00e9ton d\u2019environ 40 % pour le dioxyde d'azote (NO2) et de 50 %\npour les particules PM10.</p>",
			"main": "<p>En v\u00e9lo, \u00e9viter les gaz d'\u00e9chappement : il est conseill\u00e9 de se placer devant\nles voitures au feu rouge et de garder ses distances lorsque l'on suit un\nv\u00e9hicule motoris\u00e9.</p>"
		},
		"indice": {
			"color": "#FF5050",
			"details": [{
				"indice": {
					"color": "#FF5050",
					"label": "Mauvais",
					"value": 4
				},
				"label": "PM2,5"
			}, {
				"indice": {
					"color": "#F0E641",
					"label": "D\u00e9grad\u00e9",
					"value": 3
				},
				"label": "PM10"
			}, {
				"indice": {
					"color": "#50CCAA",
					"label": "Moyen",
					"value": 2
				},
				"label": "NO2"
			}, {
				"indice": {
					"color": "#50F0E6",
					"label": "Bon",
					"value": 1
				},
				"label": "O3"
			}, {
				"indice": {
					"color": "#50F0E6",
					"label": "Bon",
					"value": 1
				},
				"label": "SO2"
			}],
			"label": "Mauvais",
			"value": 4
		},
		"sources": [{
			"label": "Airparif",
			"url": "https://www.airparif.asso.fr/"
		}],
		"validity": {
			"area": "Paris",
			"end": "2022-01-15T23:59:59",
			"start": "2022-01-15T00:00:00"
		}
	},
```

Les dates de validité sont bien celles du jour.

Airparif a aussi un historique :
<img width="725" alt="paris-airparif-20220115" src="https://user-images.githubusercontent.com/23194091/149901203-373bf805-5abe-406e-b50c-743fb9a04b3f.png">

Si on se fie à cela, il y a des différences pour :
- NO2 : Moyen chez Recosanté, Dégradée sur Airparif
- PM2,5 : Mauvais chez Recosanté, Très mauvaise sur Airparif
- PM10 : Dégradé chez Recosanté, Mauvaise chez Airparif

1 niveau de décalage pour les 3. Déjà vu qqch de similaire par le passé ?

**Comment by annepoirot** [comment]
Oui on a déjà eu des cas similaires, liés à l'actualisation des données. Les données étant actualisées au plus tard à 14h chaque jour, nous utilisons les prévisions de la veille. On peut donc avoir des cas où l'indice qu'on envoie par mail est "Mauvais" quand en réalité il sera actualisé ensuite en "Très mauvais". 

Attention, les seuils de l'indice ATMO et des épisodes de pollution ne sont pas alignés : on peut avoir un indice ATMO "Très mauvais" sans pour autant qu'il y ait un épisode de pollution déclenché => mais c'est rare.

**Comment by florianpanchout** [comment]
Si jamais : les données n'étaient pas bonnes matin et après-midi (et Airparif indiquait bien un épisode de pollution en cours sur Paris)

**Comment by fcoufour** [comment]
Merci pour vos retours à tous les 2. On peut voir ici les épisodes de pollution aux particules PM10 du 14/01 et du 15/01 en Île-de France : https://data-airparif-asso.opendata.arcgis.com/datasets/alrt-idf/explore?location=-0.000000%2C0.000000%2C2.81&showTable=true. Ces 2 épisodes n'ont pas été enregistrés en base chez Recosanté, contrairement au précédent, celui du 14/10.
Cela s'explique par le fait que **l'authentification au service spécifique qui nous alimente n'était plus fonctionnelle**.
C'est à présent rétabli.
👉 Action qui rentre dans les objectifs de janvier : **mieux monitorer les dépendances externes majeures pour faciliter la maintenance de Recosanté**.

Deuxième sujet, les différences sur les indices de pollution.
Comme pour les épisodes de pollution, nous affichons les indices qui concernent la date du jour pour la date de diffusion la plus récente. Autrement dit, on devrait avoir les données les plus fraîches. Or les indices en base sont différents de ceux envoyés par l'API pour cette date. L'hypothèse la plus plausible, c'est qu'Airparif met à jour les indices en ne mettant pas à jour la date de diffusion (précision à la journée). Jusqu'à maintenant, lorsque la date de diffusion restait inchangée, les indices n'étaient pas mis à jour en base. **A partir de maintenant, on mettra à jour ces données y compris si la date de diffusion reste inchangée**.
👉 **Hypothèse à vérifier avec notre partenaire** @annepoirot
